### ISSUE TITLE
List of options and validating them

### ISSUE THREAD

**Issue by 0gust1** [metricsgraphics/react-metrics-graphics#23]
Hi,

I'm currently working on a lightweight wrapper for VueJS, in the same spirit of your wrapper.  
(https://github.com/0gust1/vue-metrics-graphics , still nothing released atm).

I would like to implement props validation on vueJS side too, but it's a bit cumbersome : there are a lot of possible options and on the metricsgraphics documentation, you have to browse each of them to see the type and the default value. Do you know a way to have this (all the possible options, their types and default value) in **one** document ?

Thanks for your work, BTW, it already helped to elaborate my wrapper !

**Comment by wlach** [comment]
@0gust1 good question! I think there might be an argument for defining this information inside metricsgraphics itself, maybe as a property of the export. Then react or vue bindings could just grab the set of supported bindings automatically (and maybe we could even generate documentation from it) @hamilton, what do you think?

**Comment by 0gust1** [comment]
@wlach seem a good idea from my POV.
Small related question : why is there `point-size` two times at https://github.com/metricsgraphics/react-metrics-graphics/blob/master/src/components/MetricsGraphics.js#L64 ?

On our subject, I can implement props validation in the vuejs wrapper, but it will take me some time to gather the 100+ requirements :)

**Comment by wlach** [comment]
Still thinking about this, I'm increasingly feeling like it's a good idea.

**Comment by wlach** [comment]
Filed an issue in metrics graphics itself about doing this: https://github.com/metricsgraphics/metrics-graphics/issues/875

Hopefully we can get to it soon. :) Would be great to make metricsgraphics easier to use from libraries like vue.
