### ISSUE TITLE
Issues with required versions of peer dependencies (react, react-dom)

### ISSUE THREAD

**Issue by ecomerford** [metricsgraphics/react-metrics-graphics#24]
Using react-metrics-graphics v.1.0.3:

The terminal is telling me that the library requires react and react-DOM v.0.14.0 or higher, but when I install anything higher than this, I'm hit with the same error:

```
npm WARN react-metrics-graphics@1.0.3 requires a peer of react@^0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-metrics-graphics@1.0.3 requires a peer of react-dom@^0.14.0 but none is installed. You must install peer dependencies yourself.
```

I have react and react-dom v. 15.6.0 installed currently. If I install version 0.14.0, it fixes the dependencies issue with react-metrics-graphics, but I'm getting this error to the console:

```
Warning: Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types
```
According to the [link](http://fb.me/use-check-prop-types), this is because my version of react is incompatible with the `prop-types` package. So, unfortunately, just installing an older version isn't sufficient to fix the problem.

Any thoughts on what I should do here?

**Comment by wlach** [comment]
Thanks for the report @ecomerford -- these are all problems on my end (poorly specified peerDependencies and incorrect calling of PropTypes). I'll fix these problems and release a new version today.
