### ISSUE TITLE
Add zooming options

### ISSUE THREAD

**Issue by wlach** [metricsgraphics/react-metrics-graphics#30]
In order for projects like [missioncontrol](https://github.com/mozilla/missioncontrol/) to be able to use the new brushing/zooming functionality, we'll need to add the new brushing/zooming properties to the list of supported properties by this package:

https://github.com/metricsgraphics/react-metrics-graphics/blob/master/README.md#properties
https://github.com/metricsgraphics/react-metrics-graphics/blob/master/src/components/MetricsGraphics.jsx#L6

@cnwangjie is this something you might want to take care of? Should be a relatively straightforward task. :)

(it would be nice if we didn't have to do this, see #23 -- but I don't think it's worth blocking this functionality on that larger solution being implemented)

**Comment by cnwangjie** [comment]
@wlach It's my pleasure to do it. I've submitted a PR to add the options for zooming.

As #23, currently we must modify the array here whenever the available options change. I think we can avoid a repeat. Maybe we can export a list of available options in metrics-graphics. It is already an object. We just need to export it simply and we can easily pack it into a single component for React or Vue.

**Comment by wlach** [comment]
Fixed with #32, thank you @cnwangjie 

I filed https://github.com/metricsgraphics/metrics-graphics/issues/875 as a followup to export the list of options from metrics graphics itself.
